server:
  forward-headers-strategy: native
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      use-suffix-pattern: true
  jackson:
    data-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      force: true

# 設定 Hibernate
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

# ddl-auto 有 none(預設) / create / create-drop / update / validate / create-only / drop
# create 代表每次加載 hibernate 時會刪除舊表，(根據 model)創建新表
# create-drop 則除了 create 外，在結束 (sessionFactory 關閉) 時會刪除表格
# update 是第一次運行時會建立新表，若 model 改變時，表格會重新建立，但資料保留；餘類推。
    hibernate:
      ddl-auto: update

